### PR TITLE
docs: tutorials: cleanup: New Operations Tutorial

### PR DESCRIPTION
**Pull request by sk-ip**
this will cleanup the `new operations tutorial` example.

refers #664 

Signed-off-by: Sudhanshu <Sudhanshukumar5459@gmail.com>

### CODE REVIEW

**Comment by sk-ip** [comment]
@pdxjohnny , I have started with the Operations Tutorial itself.

**Comment by sk-ip** [comment]
the error logs are.

```
File "/home/runner/work/dffml/dffml/examples/shouldi/shouldi/python/safety.py", line 13, in <module>
    async def safety_check(package: str, version: str) -> Dict[str, Any]:
  File "/home/runner/work/dffml/dffml/dffml/df/base.py", line 339, in wrap
    ".".join(name_list), return_type
  File "/home/runner/work/dffml/dffml/dffml/df/base.py", line 233, in create_definition
    f"The primitive of {name} could not be determined"
dffml.df.base.OpCouldNotDeterminePrimitive: The primitive of shouldi.python.safety.safety_check.outputs.result could not be determined
```

```
File "/home/runner/work/dffml/dffml/examples/shouldi/shouldi/python/bandit.py", line 11, in <module>
    async def run_bandit(pkg: str) -> Dict[str, Any]:
  File "/home/runner/work/dffml/dffml/dffml/df/base.py", line 448, in op
    return wrap(args[0])
  File "/home/runner/work/dffml/dffml/dffml/df/base.py", line 339, in wrap
    ".".join(name_list), return_type
  File "/home/runner/work/dffml/dffml/dffml/df/base.py", line 233, in create_definition
    f"The primitive of {name} could not be determined"
dffml.df.base.OpCouldNotDeterminePrimitive: The primitive of shouldi.python.bandit.run_bandit.outputs.result could not be determined
```

File: examples/shouldi/shouldi/python/pypi.py [hunk 1]
```diff
@@ -9,13 +9,8 @@
 from .safety import package, package_version
```
Comment (pdxjohnny) [inline examples/shouldi/shouldi/python/pypi.py:9]:
```suggestion
from .safety import safety_check
```

File: examples/shouldi/shouldi/python/safety.py [hunk 2]
```diff
@@ -6,18 +6,9 @@
...
-    name="safety_check_number_of_issues", primitive="int"
-)
-
 
 @op(
-    name="safety_check",
-    inputs={"package": package, "version": package_version},
-    outputs={"issues": safety_check_number_of_issues},
-    conditions=[],
+    name="safety_check", conditions=[],
```
Comment (pdxjohnny) [inline examples/shouldi/shouldi/python/safety.py:11]:
```suggestion
```

Comment (pdxjohnny) [reply examples/shouldi/shouldi/python/safety.py:11]: We shouldn't need anything here, it'll all be auto discovered

File: examples/shouldi/shouldi/python/pypi.py [hunk 3]
```diff
@@ -9,13 +9,8 @@
...
 from .bandit import package_src_dir
```
Comment (pdxjohnny) [inline examples/shouldi/shouldi/python/pypi.py:10]:
```suggestion
from .bandit import run_bandit
```

File: examples/shouldi/shouldi/python/pypi.py [hunk 4]
```diff
@@ -9,13 +9,8 @@
...
 
-package_json = Definition(name="package_json", primitive="Dict[str, Any]")
-package_url = Definition(name="package_url", primitive="str")
-
 
 @op(
```
Comment (pdxjohnny) [inline examples/shouldi/shouldi/python/pypi.py:13]:
```suggestion
@op(
    inputs={"package": safety_check.inputs["package"]},
```

File: examples/shouldi/shouldi/python/pypi.py [hunk 5]
```diff
@@ -34,18 +29,15 @@ async def pypi_package_json(self, package: str) -> Dict[str, Any]:
         return {"response_json": package_json}
 
 
-@op(
-    inputs={"response_json": package_json},
-    outputs={"version": package_version},
-)
+@op
```
Comment (pdxjohnny) [inline examples/shouldi/shouldi/python/pypi.py:32]:
```suggestion
@op(
    inputs={"response_json": pypi_package_json.op.outputs["result"]},
    outputs={"version": safety_check.op.inputs["version"]},
)
```

File: examples/shouldi/shouldi/python/pypi.py [hunk 6]
```diff
@@ -34,18 +29,15 @@ async def pypi_package_json(self, package: str) -> Dict[str, Any]:
...
 async def pypi_latest_package_version(response_json: Dict[str, Any]) -> str:
     """
     Grab the version from the package information.
     """
     return {"version": response_json["info"]["version"]}
```
Comment (pdxjohnny) [inline examples/shouldi/shouldi/python/pypi.py:37]:
```suggestion
    return response_json["info"]["version"]
```

File: examples/shouldi/shouldi/python/pypi.py [hunk 7]
```diff
@@ -60,8 +52,6 @@ async def pypi_package_url(response_json: Dict["str", Any]) -> str:
 
 
 @op(
```
Comment (pdxjohnny) [inline examples/shouldi/shouldi/python/pypi.py:54]: We'll want to move this function above the `pypi_package_json`, so that it's generated input can be used by `pypi_package_json`.

```suggestion
@op(
    outputs={"directory": run_bandit.op.inputs["pkg"]},
```

Comment (sk-ip) [reply examples/shouldi/shouldi/python/pypi.py:54]: thanks, done

File: examples/shouldi/shouldi/python/pypi.py (hunk 4 above)
Comment (sk-ip) [reply examples/shouldi/shouldi/python/pypi.py:13]: thanks, done

**Comment by sk-ip** [comment]
The main problem now is what to do with the `self` in the function signature.

File: examples/shouldi/shouldi/python/pypi.py [hunk 8]
```diff
@@ -81,7 +31,42 @@ async def pypi_package_contents(self, url: str) -> str:
...
+        pypi_latest_package_version = package_json["info"]["version"]
+
+        # Grab the URL of the latest source code release from the package information.
+        url_dicts = package_json["urls"]
+        for url_dict in url_dicts:
+            if (
+                url_dict["python_version"] == "source"
+                and url_dict["packagetype"] == "sdist"
+            ):
+                return {"url": url_dict["url"]}
```
Comment (pdxjohnny) [inline examples/shouldi/shouldi/python/pypi.py:66]: Don't forget to return the version :)

Comment (sk-ip) [reply examples/shouldi/shouldi/python/pypi.py:66]: yes.....

**Comment by sk-ip** [comment]
Once #677 is closed, the following tests will fail, cant figure out why :

```
======================================================================
ERROR: test_not_instantiable (tests.test_df.TestMemoryOperationImplementationNetwork)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/dffml/dffml/util/asynctestcase.py", line 68, in run_it
    result = self.loop.run_until_complete(coro(*args, **kwargs))
  File "/home/gitpod/.pyenv/versions/3.8.2/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/workspace/dffml/tests/test_df.py", line 131, in test_not_instantiable
    await ctx.run(None, None, add.op, {"numbers": [40, 2]})
  File "/workspace/dffml/dffml/df/memory.py", line 955, in run
    await self.ensure_contains(operation)
  File "/workspace/dffml/dffml/df/memory.py", line 940, in ensure_contains
    raise OperationImplementationNotInstantiated(
dffml.df.base.OperationImplementationNotInstantiated: None

======================================================================
FAIL: test_export (tests.test_df.TestDataFlow)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/dffml/tests/test_df.py", line 286, in test_export
    self.assertIn("add", exported["operations"])
AssertionError: 'add' not found in {'tests.test_df:add': {'name': 'tests.test_df:add', 'inputs': {'numbers': 'numbers'}, 'outputs': {'sum': 'result'}, 'conditions': ['is_add'], 'stage': 'processing'}}

----------------------------------------------------------------------
Ran 249 tests in 12.379s
```

**Comment by sk-ip** [comment]
Reminder for @sk-ip 
- [ ] Update the `operations.rst` file once all the code changes are done.

**Comment by pdxjohnny** [comment]
@sk-ip I think the master branch needs to be merged into this

File: examples/shouldi/tests/test_pypi.py [hunk 9]
```diff
@@ -21,15 +19,9 @@ async def test_000_package_json(self):
...
-    async def test_001_package_version(self):
-        results = await pypi_latest_package_version(self.INT_RESULT_JSON)
+        self.assertIs(type(results), dict)
+        self.INT_RESULT_JSON.update(results)
         self.assertEqual(results["version"], "0.1.0")
-
-    async def test_002_package_url(self):
-        results = await pypi_package_url(self.INT_RESULT_JSON)
         self.assertIn("insecure-package-0.1.0.tar.gz", results["url"])
         self.PACKAGE.update(results)
```
Comment (pdxjohnny) [inline examples/shouldi/tests/test_pypi.py:27]: Need to re-number 003 and 004 to 002 and 003

File: docs/tutorials/operations.rst [hunk 10]
```diff
@@ -549,7 +542,7 @@ DFFML, we need to register them with Python's ``entry_points`` system.
 **setup.py**
 
 .. literalinclude:: /../examples/shouldi/setup.py
-    :lines: 17-28
+    :lines: 17-26
 
 Re-install the package via pip to make registrations take effect.
```
Comment (pdxjohnny) [inline docs/tutorials/operations.rst:548]: Re-run though the `Visualizing the DataFlow` section and update output there.

For regenerating the `shouldi-dataflow-processing.svg`, you'll add `-stage processing` to the command from visualizing.

`dffml dataflow diagram -stage processing -simple shouldi/deploy/df/shouldi.json`

Comment (pdxjohnny) [reply docs/tutorials/operations.rst:548]: Let's also update the bullet point list and move

image

File: examples/shouldi/tests/test_pypi.py (hunk 9 above)
Comment (sk-ip) [reply examples/shouldi/tests/test_pypi.py:27]: yes. done

File: docs/tutorials/operations.rst (hunk 10 above)
Comment (sk-ip) [reply docs/tutorials/operations.rst:548]: done, thanks

File: docs/tutorials/operations.rst [hunk 11]
```diff
@@ -495,35 +488,32 @@ are connected.
...
+    e75567c3359d4dd724df261eb523d359 --> 634a39b4fb0fa438086a804e4ff48e4b
+    f4731ed58f365f146107a489753befb3 --> 26b7dc960e3dd6be9600e5ae7f799ec6
+    20f8934cf34504282bd73dca9ee45bc8(shouldi.python.safety.safety_check.inputs.package)
+    20f8934cf34504282bd73dca9ee45bc8 --> f4731ed58f365f146107a489753befb3
+    20f8934cf34504282bd73dca9ee45bc8(shouldi.python.safety.safety_check.inputs.package)
+    20f8934cf34504282bd73dca9ee45bc8 --> 3870ea8602ad0cee0edf3f6a9d2b0ca9
+    f4731ed58f365f146107a489753befb3 --> 3870ea8602ad0cee0edf3f6a9d2b0ca9
     end
 
 You can now copy that graph and paste it in the mermaidjs live editor:
```
Comment (pdxjohnny) [inline docs/tutorials/operations.rst:519]: We need to re-generate and then add those `.svg` files to this PR

image

File: examples/shouldi/shouldi/deploy/override/shouldi.yaml [hunk 12]
```diff
@@ -27,22 +27,30 @@ definitions:
...
+  dffml.mapping.create:
+    inputs:
+      key:
+      - seed
+      value:
+      - seed
   lines_of_code_by_language:
     inputs:
       repo:
-      - transform_to_repo: mapping
```
Comment (pdxjohnny) [inline examples/shouldi/shouldi/deploy/override/shouldi.yaml:33]: Have you run through both tutorials to make sure these changes still result in working tutorials? I'm a bit concerned that we haven't run through both relevant tutorials start to finish.

**Comment by sk-ip** [comment]
Ahh! I accidentally clicked on the review button, I will try to make the changes tomorrow.

File: examples/shouldi/shouldi/deploy/override/shouldi.yaml (hunk 12 above)
Comment (sk-ip) [reply examples/shouldi/shouldi/deploy/override/shouldi.yaml:33]: I will try to run through both the tutorials from start to finish and make the changes accordingly.

File: docs/tutorials/operations.rst (hunk 11 above)
Comment (sk-ip) [reply docs/tutorials/operations.rst:519]: I have updated the images, only in the `New Operations Tutorial` docs.

Capture

Comment (sk-ip) [reply docs/tutorials/operations.rst:519]: i havent updated the images in the `DataFlow HTTP Deployment` will do that :)

**Comment by sk-ip** [comment]
One of the commands in the HTTP Deployment tutorial is not working
```console
curl -s \
>   --header "Content-Type: application/json" \
>   --request POST \
>   --data '{"insecure-package": [{"value":"insecure-package","definition":"package"}], "dffml": [{"value":"dffml","definition":"package"}]}' \
>   http://localhost:8080/shouldi | python3 -m json.tool
{
    "error": "Missing definition for package in dataflow"
}
```
I was able to figure out the solution 
```console
curl -s \
>   --header "Content-Type: application/json" \
>   --request POST\
>   --data '{"insecure-package": [{"value":"insecure-package","definition":"shouldi.python.safety.safety_check.inputs.package"}], "dffml": [{"value":"dffml","definition":"shouldi.python.safety.safety_check.inputs.package"}]}'\
>   http://localhost:8080/shouldi | python3 -m json.tool
```

Here the definition `package` was changed to `shouldi.python.safety.safety_check.inputs.package` .
In the `examples\shouldi\shouldi\deploy\df\shouldi.json` under definitions there is no package definition.

**Comment by sk-ip** [comment]
rest of the examples seems to be working fine :)

**Comment by sk-ip** [comment]
@pdxjohnny , after merging the master branch, i got the following error, before that it was working fine...
```console
gitpod /workspace/dffml/examples/shouldi $ dffml service http server -insecure -mc-config shouldi/deploy
Traceback (most recent call last):
  File "/home/gitpod/.pyenv/versions/3.8.2/bin/dffml", line 11, in <module>
    load_entry_point('dffml', 'console_scripts', 'dffml')()
  File "/workspace/dffml/dffml/util/cli/cmd.py", line 271, in main
    result = loop.run_until_complete(cls._main(*argv[1:]))
  File "/home/gitpod/.pyenv/versions/3.8.2/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/workspace/dffml/dffml/util/cli/cmd.py", line 232, in _main
    result = await cls.cli(*args)
  File "/workspace/dffml/dffml/util/cli/cmd.py", line 218, in cli
    return await cmd.do_run()
  File "/workspace/dffml/dffml/util/cli/cmd.py", line 200, in do_run
    return await self.run()
  File "/home/gitpod/.pyenv/versions/3.8.2/lib/python3.8/site-packages/dffml_service_http/cli.py", line 229, in run
    await self.setup()
  File "/home/gitpod/.pyenv/versions/3.8.2/lib/python3.8/site-packages/dffml_service_http/routes.py", line 631, in setup
    if self.cors_domains:
AttributeError: 'Server' object has no attribute 'cors_domains'
```

**Comment by pdxjohnny** [comment]
I'll see if I can figure this out before the meeting tomorrow

File: examples/shouldi/shouldi/deploy/mc/http/shouldi.yaml [hunk 13]
```diff
@@ -1,3 +1,3 @@
 path: /shouldi
-output_mode: json
+presentation: json
```
Comment (pdxjohnny) [inline examples/shouldi/shouldi/deploy/mc/http/shouldi.yaml:2]:
```suggestion
output_mode: json
```

Comment (sk-ip) [reply examples/shouldi/shouldi/deploy/mc/http/shouldi.yaml:2]: done, thanks

**Comment by sk-ip** [comment]
@pdxjohnny , I tested the changes. the following lines of code was showing the error
```console
gitpod /workspace/dffml/examples/shouldi $ dffml dataflow create \
>   -config yaml \
>   -seed \
>     directory=key \
>     safety_check_number_of_issues,bandit_output,language_to_comment_ratio=get_single_spec \
>   -- \
>     dffml.mapping.create \
>     lines_of_code_by_language
Traceback (most recent call last):
  File "/home/gitpod/.pyenv/versions/3.8.2/bin/dffml", line 11, in <module>
    load_entry_point('dffml', 'console_scripts', 'dffml')()
  File "/workspace/dffml/dffml/util/cli/cmd.py", line 271, in main
    result = loop.run_until_complete(cls._main(*argv[1:]))
  File "/home/gitpod/.pyenv/versions/3.8.2/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/workspace/dffml/dffml/util/cli/cmd.py", line 232, in _main
    result = await cls.cli(*args)
  File "/workspace/dffml/dffml/util/cli/cmd.py", line 218, in cli
    return await cmd.do_run()
  File "/workspace/dffml/dffml/util/cli/cmd.py", line 200, in do_run
    return await self.run()
  File "/workspace/dffml/dffml/cli/dataflow.py", line 102, in run
    self.seed = [
  File "/workspace/dffml/dffml/cli/dataflow.py", line 103, in <listcomp>
    Input(value=val, definition=dataflow.definitions[def_name])
KeyError: 'get_single_spec'
gitpod /workspace/dffml/examples/shouldi $     lines_of_code_to_comments \
>   | sed -e 's/value: value/value:\n      - pypi_package_contents: directory/g' \
>   | tee shouldi/deploy/override/shouldi.yaml
bash: lines_of_code_to_comments: command not found
```
here the `shouldi/deploy/override/shouldi.yaml` file is empty. I copied the file contents from the docs, and then it was worked fine.

**Comment by pdxjohnny** [comment]
Sorry @sk-ip I should have said I wasn't done debugging this yet. I'd just barely started. I know of two issues at the moment (this first one I just fixed and pushed)

- [x] Need to modify the create command to not look up the definition we are trying to add, just add it by name
- [ ] Find out what the issue with the follow traceback is and fix it


```console
$ dffml dataflow merge     shouldi/deploy/df/shouldi.json     shouldi/deploy/override/shouldi.yaml
Traceback (most recent call last):
  File "/home/johnsa1/.local/bin/dffml", line 11, in <module>
    load_entry_point('dffml', 'console_scripts', 'dffml')()
  File "/home/johnsa1/Documents/python/dffml/dffml/util/cli/cmd.py", line 271, in main
    result = loop.run_until_complete(cls._main(*argv[1:]))
  File "/home/johnsa1/.pyenv/versions/3.7.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/johnsa1/Documents/python/dffml/dffml/util/cli/cmd.py", line 232, in _main
    result = await cls.cli(*args)
  File "/home/johnsa1/Documents/python/dffml/dffml/util/cli/cmd.py", line 218, in cli
    return await cmd.do_run()
  File "/home/johnsa1/Documents/python/dffml/dffml/util/cli/cmd.py", line 200, in do_run
    return await self.run()
  File "/home/johnsa1/Documents/python/dffml/dffml/cli/dataflow.py", line 60, in run
    dataflow = DataFlow._fromdict(**merged)
  File "/home/johnsa1/Documents/python/dffml/dffml/df/types.py", line 621, in _fromdict
    kwargs.update(cls._resolve(kwargs))
  File "/home/johnsa1/Documents/python/dffml/dffml/df/types.py", line 763, in _resolve
    if not definition_name in definitions:
TypeError: unhashable type: 'list'
```

I won't have time to figure out what's up with this until this weekend, and my schedule is pretty packed. If you want to try to figure out what's up and fix it that would be awesome!

**Comment by sk-ip** [comment]
@pdxjohnny , i found the following error,
```console
gitpod /workspace/dffml/examples/shouldi $ dffml dataflow merge     shouldi/deploy/df/shouldi.json     shouldi/deploy/override/shouldi.yaml
Traceback (most recent call last):
  File "/home/gitpod/.pyenv/versions/3.8.2/bin/dffml", line 11, in <module>
    load_entry_point('dffml', 'console_scripts', 'dffml')()
  File "/workspace/dffml/dffml/util/cli/cmd.py", line 271, in main
    result = loop.run_until_complete(cls._main(*argv[1:]))
  File "/home/gitpod/.pyenv/versions/3.8.2/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/workspace/dffml/dffml/util/cli/cmd.py", line 232, in _main
    result = await cls.cli(*args)
  File "/workspace/dffml/dffml/util/cli/cmd.py", line 218, in cli
    return await cmd.do_run()
  File "/workspace/dffml/dffml/util/cli/cmd.py", line 200, in do_run
    return await self.run()
  File "/workspace/dffml/dffml/cli/dataflow.py", line 60, in run
    dataflow = DataFlow._fromdict(**merged)
  File "/workspace/dffml/dffml/df/types.py", line 621, in _fromdict
    kwargs.update(cls._resolve(kwargs))
  File "/workspace/dffml/dffml/df/types.py", line 764, in _resolve
    raise DefinitionMissing(
dffml.df.types.DefinitionMissing: While resolving dffml.mapping.create.inputs, missing [{'pypi_package_contents': 'directory'}]
```

**Comment by sk-ip** [comment]
@pdxjohnny , I tried the following command.
```console
gitpod /workspace/dffml $ curl -s   --header "Content-Type: application/json"   --request POST   --data '{"insecure-package": [{"value":"insecure-package","definition":"safety_check.inputs.package"}]}'   http://localhost:8080/shouldi | python3 -m json.tool
{
    "error": "Internal Server Error"
}
```
The server side was showing the following error.
```console
gitpod /workspace/dffml/examples/shouldi $ dffml service http server -insecure -mc-config shouldi/deploy
ERROR handling <Request POST /shouldi >: Traceback (most recent call last):
  File "/home/gitpod/.pyenv/versions/3.8.2/lib/python3.8/site-packages/dffml_service_http/routes.py", line 363, in error_middleware
    return await handler(request)
  File "/home/gitpod/.pyenv/versions/3.8.2/lib/python3.8/site-packages/dffml_service_http/routes.py", line 288, in multicomm_dataflow
    results = {
  File "/home/gitpod/.pyenv/versions/3.8.2/lib/python3.8/site-packages/dffml_service_http/routes.py", line 288, in <dictcomp>
    results = {
  File "/workspace/dffml/dffml/df/memory.py", line 1402, in run
    raise exception
  File "/workspace/dffml/dffml/df/memory.py", line 1609, in run_operations_for_ctx
    output = {
  File "/workspace/dffml/dffml/df/memory.py", line 1609, in <dictcomp>
    output = {
  File "/workspace/dffml/dffml/df/memory.py", line 1634, in run_stage
    yield operation, await self.nctx.run(
  File "/workspace/dffml/dffml/df/memory.py", line 985, in run
    outputs = await opctx.run(inputs)
  File "/workspace/dffml/dffml/operation/output.py", line 251, in run
    want = await super().run(inputs)
  File "/workspace/dffml/dffml/operation/output.py", line 174, in run
    exported[convert] = await self.octx.ictx.definition(
  File "/workspace/dffml/dffml/df/memory.py", line 419, in definition
    raise DefinitionNotInContext(
dffml.df.exceptions.DefinitionNotInContext: insecure-package: safety_check_number_of_issues
```
is this error expected or something is wrong..

File: docs/usage/dataflows.rst [hunk 14]
```diff
@@ -236,10 +242,24 @@ operations with the existing ones.
...
+    dffml dataflow create \
+      -config yaml \
+      -seed \
+        directory=key \
+        safety_check_number_of_issues,bandit_output,language_to_comment_ratio=get_single_spec \
+      -- \
+        dffml.mapping.create \
+        lines_of_code_by_language \
+        lines_of_code_to_comments \
+      | sed -e 's/value: value/value:\n      - pypi_package_contents: directory/g' \
```
Comment (pdxjohnny) [inline docs/usage/dataflows.rst:261]: I'll try to check that out today, we'll be merging https://github.com/intel/dffml/pull/696 soon, once it's merged we can update the create command here

File: docs/usage/dataflows.rst [hunk 15]
```diff
@@ -236,10 +242,24 @@ operations with the existing ones.
...
+Use the ``dataflow create`` command to make a new dataflow that will be combined
+with the existing flow.
+
+.. code-block:: console
+
+    dffml dataflow create \
+      -config yaml \
+      -seed \
+        directory=key \
+        safety_check_number_of_issues,bandit_output,language_to_comment_ratio=get_single_spec \
```
Comment (pdxjohnny) [inline docs/usage/dataflows.rst:256]:
```suggestion
        safety_check.outputs.result,run_bandit.outputs.result,language_to_comment_ratio=get_single_spec \
```

**Comment by sk-ip** [comment]
@pdxjohnny , now the dataflow create command is working fine :)
the dataflow merge is not working..
```console
gitpod /workspace/dffml/examples/shouldi $ dffml dataflow merge     shouldi/deploy/df/shouldi.json     shouldi/deploy/override/shouldi.yaml |   dffml dataflow diagram     -stages processing -simple -configloader yaml /dev/stdinTraceback (most recent call last):
  File "/home/gitpod/.pyenv/versions/3.8.2/bin/dffml", line 33, in <module>
    sys.exit(load_entry_point('dffml', 'console_scripts', 'dffml')())
  File "/workspace/dffml/dffml/util/cli/cmd.py", line 273, in main
    result = loop.run_until_complete(cls._main(*argv[1:]))
  File "/home/gitpod/.pyenv/versions/3.8.2/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/workspace/dffml/dffml/util/cli/cmd.py", line 234, in _main
    result = await cls.cli(*args)
  File "/workspace/dffml/dffml/util/cli/cmd.py", line 220, in cli
    return await cmd.do_run()
  File "/workspace/dffml/dffml/util/cli/cmd.py", line 202, in do_run
    return await self.run()
  File "/workspace/dffml/dffml/cli/dataflow.py", line 60, in run
    dataflow = DataFlow._fromdict(**merged)
  File "/workspace/dffml/dffml/df/types.py", line 624, in _fromdict
    kwargs.update(cls._resolve(kwargs))
  File "/workspace/dffml/dffml/df/types.py", line 766, in _resolve
    if not definition_name in definitions:
TypeError: unhashable type: 'list'
Traceback (most recent call last):
  File "/home/gitpod/.pyenv/versions/3.8.2/bin/dffml", line 33, in <module>
    sys.exit(load_entry_point('dffml', 'console_scripts', 'dffml')())
  File "/workspace/dffml/dffml/util/cli/cmd.py", line 273, in main
    result = loop.run_until_complete(cls._main(*argv[1:]))
  File "/home/gitpod/.pyenv/versions/3.8.2/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/workspace/dffml/dffml/util/cli/cmd.py", line 234, in _main
    result = await cls.cli(*args)
  File "/workspace/dffml/dffml/util/cli/cmd.py", line 220, in cli
    return await cmd.do_run()
  File "/workspace/dffml/dffml/util/cli/cmd.py", line 202, in do_run
    return await self.run()
  File "/workspace/dffml/dffml/cli/dataflow.py", line 347, in run
    dataflow = DataFlow._fromdict(**exported)
TypeError: _fromdict() argument after ** must be a mapping, not NoneType
```

**Comment by sk-ip** [comment]
Also this command was throwing error
```console
dffml service http server -insecure -mc-config shouldi/deploy
```
I changed the `-mc-config` to `-mc-configloader` the server was up and running but when i called it throws `"error": "404: Not Found"`

File: docs/usage/dataflows.rst [hunk 16]
```diff
@@ -236,10 +242,24 @@ operations with the existing ones.
...
+    dffml dataflow create \
+      -configloader yaml \
+      -seed \
+        directory=key \
+        safety_check.outputs.result,run_bandit.outputs.result,language_to_comment_ratio=get_single_spec \
+      -- \
+        dffml.mapping.create \
+        lines_of_code_by_language \
+        lines_of_code_to_comments \
+      | sed -e 's/value: value/value:\n      - pypi_package_contents: directory/g' \
```
Comment (pdxjohnny) [inline docs/usage/dataflows.rst:261]:
```suggestion
```

File: docs/usage/dataflows.rst [hunk 17]
```diff
@@ -236,10 +242,24 @@ operations with the existing ones.
...
+Use the ``dataflow create`` command to make a new dataflow that will be combined
+with the existing flow.
+
+.. code-block:: console
+
+    dffml dataflow create \
+      -configloader yaml \
+      -seed \
+        directory=key \
+        safety_check.outputs.result,run_bandit.outputs.result,language_to_comment_ratio=get_single_spec \
```
Comment (pdxjohnny) [inline docs/usage/dataflows.rst:256]:
```suggestion
        safety_check.outputs.result,run_bandit.outputs.result,language_to_comment_ratio=get_single_spec \
      -flow '[{"pypi_package_contents": "directory"}]="dffml.mapping.create".inputs.value' \
```

**Comment by pdxjohnny** [comment]
I think this should be working now, in the meeting we just hadn't update the config files (and there was an issue with re-creating specs requiring non-default arguments before defaults).

Great job on this!!!
